language: objective-c
osx_image: xcode7.3

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

env:
  #- RAKETASK="simlist"
  #- RAKETASK="ios[iOS StaticLib,7.1,test]"
  - RAKETASK="ios[iOS StaticLib,latest,test]"
  - RAKETASK="ios[iOS Framework,latest,test]"
  - RAKETASK="osx[Mac Framework,x86_64,test]"
  - RAKETASK="tvos[tvOS Framework,latest,test]"

script:
  - rake "$RAKETASK"

before_deploy:
  - carthage build --no-skip-current
  - carthage archive OHHTTPStubs

deploy:
  provider: releases
  api_key:
    secure: LJfogUcxlaXczvPyu+s2SAG7SXyhjQbc/kCiNjEO61ehLg0dK0bmfXHm0yeBQQPoQCF5qiWC+5HYQnCaMNmEhP4WHy6RZtmmrg1iiNbeLsRzk8COm2vv+zRgoFXU5K7j2LkfvTSrLPTYR1d+PM/S/XJzMDxrJjryM+mf12DxlnA=
  file: OHHTTPStubs.framework.zip
  skip_cleanup: true
  on:
    tags: true
